package wbdk;

/**
 * These are properties that are to be loaded from properties.xml. They will
 * provide custom labels and other UI details for our Wolfie Ball Draft Kit
 * application. The reason for doing this is to swap out UI text and icons
 * easily without having to touch our code. It also allows for language
 * independence.
 *
 * @author Sheryar
 */
public enum WBDK_PropertyType {

    // LOADED FROM properties.xml
    PROP_APP_TITLE,
    
    // APPLICATION ICONS
    NEW_DRAFT_ICON,
    LOAD_DRAFT_ICON,
    SAVE_DRAFT_ICON,
    EXPORT_DRAFT_ICON,
    EXIT_ICON,
    ADD_ICON,
    MINUS_ICON,
    EDIT_ICON,
    DRAFT_SCREEN_ICON,
    PLAYER_SCREEN_ICON,
    FANTASY_TEAM_SCREEN_ICON,
    FANTASY_TEAM_STANDING_SCREEN_ICON,
    MLB_TEAM_SCREEN_ICON,
    SELECT_PLAYER_ICON,
    AUTO_DRAFT_ICON,
    PAUSE_DRAFT_ICON,
    
    // APPLICATION TOOLTIPS FOR BUTTONS
    NEW_DRAFT_TOOLTIP,
    LOAD_DRAFT_TOOLTIP,
    SAVE_DRAFT_TOOLTIP,
    EXPORT_DRAFT_TOOLTIP,
    EXIT_TOOLTIP,
    ADD_PLAYER_TOOLTIP,
    REMOVE_PLAYER_TOOLTIP,
    DRAFT_SCREEN_TOOLTIP,
    FANTASY_TEAM_SCREEN_TOOLTIP,
    PLAYER_SCREEN_TOOLTIP,
    FANTASY_STANDING_SCREEN_TOOLTIP,
    MLB_TEAM_SCREEN_TOOLTIP,
    ADD_TEAM_TOOLTIP,
    REMOVE_TEAM_TOOLTIP,
    EDIT_TEAM_TOOLTIP,
    SELECT_PLAYER_TOOLTIP,
    AUTO_DRAFT_TOOLTIP,
    PAUSE_DRAFT_TOOLTIP,
    
    // FOR DRAFT KIT EDIT WORKSPACE
    DRAFT_HEADING_LABEL,
    FANTASY_TEAM_HEADING_LABEL,
    PLAYER_HEADING_LABEL,
    FANTASY_STANDING_HEADING_LABEL,
    MLB_TEAM_HEADING_LABEL,
    SEARCH_PLAYERS_LABEL,
    DRAFT_NAME_LABEL,
    SELECT_TEAM_LABEL,
    STARTING_LINEUP_HEADING_LABEL,
    TAXI_SQUAD_HEADING_LABEL,
    SELECT_MLB_TEAM_LABEL,
    PRO_TEAM_HEADING_LABEL,
    
    // AND VERIFICATION MESSAGES
    NEW_DRAFT_CREATED_MESSAGE,
    DRAFT_LOADED_MESSAGE,
    DRAFT_SAVED_MESSAGE,
    SITE_EXPORTED_MESSAGE,
    SAVE_UNSAVED_WORK_MESSAGE,
    REMOVE_PLAYER_MESSAGE,
    REMOVE_TEAM_MESSAGE,
    INCOMPLETE_FIELD_MESSAGE
}
